[project]
name = "bots"
version = "0.1.0"
description = "Hacker News recommendation bot with Telegram integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "beautifulsoup4",
]
