name: hn_recommender

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # 10 AM KST (UTC+9)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v6

      - run: uv sync --frozen
      - name: Run hn_recommender.py
        run: uv run python hn_recommender.py
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          CHAT_API_KEY: ${{ secrets.CHAT_API_KEY }}
          CHAT_MODEL_FAST: ${{ secrets.CHAT_MODEL_FAST }}
