name: hn_recommender

on:
  schedule:
    - cron: '0 * * * *'     # 매 정각(UTC) 실행
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v6

      - run: uv pip install -r requirements.txt
      - name: Run hn_recommender.py
        run: python hn_recommender/hn_recommender.py
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
